---
- hosts: all
  #ansadmin doesn't need root access to create an image
  become: true 

  tasks:

  - name: building docker image
    command: docker build -t simple-devops-image:latest .
    args:
      chdir: /opt/docker

  - name: docker tagging
    command: docker tag simple-devops-image kranthi003/simple-devops-image-hub
  
  - name: push image to docker
    command: docker push  kranthi003/simple-devops-image-hub

  - name: remove docker image from server
    command: docker rmi simple-devops-image:latest kranthi003/simple-devops-image-hub
    ignore_errors: yes
  

